import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      // ── 尺寸 token（2026-08 从全库任意值迁移固化）──────────────────────
      // spacing 公式：key × 4px = 实际值；调整布局只改这里，全站生效。
      spacing: {
        "0.75": "3px",
        "1.25": "5px",
        "2.75": "11px",
        "3.25": "13px",
        "4.25": "17px",
        "4.5": "18px",
        "5.25": "21px",
        "5.5": "22px",
        "10.5": "42px",
        "11.5": "46px",
        "13": "52px",
        "15": "60px",
        "17": "68px",
        "18": "72px",
        "22.5": "90px",
        "25": "100px",
        "27.5": "110px",
        "30": "120px",
        "32.5": "130px",
        "35": "140px",
        "37.5": "150px",
        "45": "180px",
        "47.5": "190px",
        "50": "200px",
        "52.5": "210px",
        "55": "220px",
        "65": "260px",
        "70": "280px",
        "75": "300px",
        "90": "360px",
        "100": "400px",
        "105": "420px",
        "120": "480px",
        "125": "500px",
        "130": "520px",
        "140": "560px",
        "150": "600px",
        "160": "640px",
        "170": "680px",
        "230": "920px",
        "240": "960px",
        "245": "980px",
      },
      // 精确字号（px 直读）：text-10 = 10px。紧凑设计的微字号体系。
      fontSize: {
        "8": "8px",
        "9": "9px",
        "10": "10px",
        "11": "11px",
        "13": "13px",
        "15": "15px",
        "22": "22px",
        "28": "28px",
        "32": "32px",
      },
      // max/min 宽高镜像 spacing 刻度（max-w-150 = 600px）
      maxWidth: ({ theme }) => ({ ...theme("spacing"), dialog: "95vw" }),
      minWidth: ({ theme }) => ({ ...theme("spacing") }),
      // 弹窗/滚动区语义尺寸
      height: { dialog: "95vh" },
      maxHeight: { dialog: "80vh", "dialog-full": "90vh" },
      width: { dialog: "95vw", "dialog-wide": "90vw" },
      borderWidth: { "1.5": "1.5px", "3": "3px" },
      ringWidth: { "3": "3px" },
      scale: { "99": "0.99", "102": "1.02" },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          blue: "hsl(var(--accent-blue))",
          "blue-light": "hsl(var(--accent-blue-light))",
          green: "hsl(var(--accent-green))",
          "green-light": "hsl(var(--accent-green-light))",
          yellow: "hsl(var(--accent-yellow))",
          "yellow-light": "hsl(var(--accent-yellow-light))",
          red: "hsl(var(--accent-red))",
          "red-light": "hsl(var(--accent-red-light))",
          purple: "hsl(var(--accent-purple))",
          "purple-light": "hsl(var(--accent-purple-light))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        content: {
          bg: "hsl(var(--content-bg))",
          "bg-secondary": "hsl(var(--content-bg-secondary))",
          text: "hsl(var(--content-text))",
          "text-secondary": "hsl(var(--content-text-secondary))",
          "text-muted": "hsl(var(--content-text-muted))",
          "text-tertiary": "hsl(var(--content-text-tertiary))",
          border: "hsl(var(--content-border))",
          "border-light": "hsl(var(--content-border-light))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        "input-background": "hsl(var(--input-background))",
        "switch-background": "hsl(var(--switch-background))",
        // 集成品牌色（Linear / Atlassian 官方色，仅用于对应 provider 标识）
        brand: {
          linear: "#5E6AD2",
          "linear-light": "#9FA8F2",
          "linear-deep": "#2D2B5F",
          "linear-darkest": "#1B1A3D",
          atlassian: "#0052CC",
          "atlassian-dark": "#0B1A33",
          "atlassian-darker": "#172B4D",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "var(--radius-control)",
        sm: "calc(var(--radius-control) - 2px)",
        xs: "2px",
        xl: "calc(var(--radius) + 4px)",
        chip: "var(--radius-chip)",
        "3": "3px",
        "5": "5px",
        "8": "8px",
        "10": "10px",
        "14": "14px",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        "slide-in-right": {
          from: {
            transform: "translateX(100%)",
          },
          to: {
            transform: "translateX(0)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in-right": "slide-in-right 0.2s ease-out",
      },
      zIndex: {
        41: "41",
        100: "100",
        110: "110",
        200: "200",
        1000: "1000",
        1001: "1001",
        9999: "9999",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
