/**
 * 组件治理登记表 —— 单一真相源（E 类方案 §5.2「三处同源」）
 *
 * 三条同源链（单向再生，禁止反向手工编辑）：
 *   ① registry.ts ──生成──► COMPONENTS.md（`node scripts/gen-components-md.mjs`）
 *   ② registry.ts ──渲染──► design-system 页（按 section 遍历 registry，覆盖率恒 100%）
 *   ③ registry.ts ──校验──► lint:registry（扫描真实引用回填 consumers，判定 LU）
 *
 * 字段口径：
 * - status 五态（canonical / standby / internal / review / deprecated）定义见
 *   docs/design/修改方案-E类-2026-09-27.md §19.3。
 * - section 采用设计系统页的四个顶层分区（Tokens / Primitives / App Components /
 *   AI Execution），组件归属按该页 SECTIONS 数组的 group 口径归类；更细的 75 个分区标签
 *   （Buttons / Cards / Forms …）留待批 4 拆分画廊时再细化。
 * - consumers 由 lint 脚本回填，本文件**不写静态值**（防推测值污染 LU 指标）。
 * - review 态必带 reviewBy；逾期须降级 deprecated 或升级 canonical（§19.3 防滥用条款）。
 * - deprecated 态必带 `expiresAt`（§19.6；由 `check-component-registry.mjs` 机器强制，逾期 CI 失败）。
 *   书写位置：紧跟 status 之后、review 块之前，如
 *   `status: 'deprecated', expiresAt: '2026-12-31', review: { … }`；`gen-components-md.mjs`
 *   与 `check-component-registry.mjs` 均已解析该槽位（2026-09-28 补齐）。
 * - `status: 'standby'` 且带 `review` 数据的条目 = 方案 §七 D 项裁决的
 *   「先标记、不删除，待人工在设计系统页审阅后裁决」集合。
 *
 * 维护约定：新增 components/ui 组件必须先在此登记，否则 lint:registry 双向对账失败。
 */

export type ComponentStatus =
  | 'canonical' | 'standby' | 'internal' | 'review' | 'deprecated'

export interface ComponentEntry {
  name: string          // 'button'
  file: string          // 'ui/button.tsx'
  section: string       // '表单' | '反馈' | '导航' | ...
  status: ComponentStatus
  variants?: string[]   // 变体轴登记（§19.4）
  consumers?: number    // 由 lint 脚本回填
  expiresAt?: string    // deprecated 必填
  reviewBy?: string     // review 必填（§19.3 防滥用）
  review?: {            // ★ 裁决面数据（承接 〇之二 三段式）
    pending: true
    reason: string      // '零引用' | '仅画廊引用' | '与 X 能力重叠' | '命名误导'
    proposal: 'delete' | 'merge' | 'keep' | 'rename' | 'standby'
    target?: string     // merge/rename 的目标组件名
  }
}

export const COMPONENT_REGISTRY: ComponentEntry[] = [
  // ── UI 原子层：src/components/ui/ ─────────────────────────────────────────
  { name: 'accordion', file: 'ui/accordion.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'activity-heatmap', file: 'ui/activity-heatmap.tsx', section: 'App Components', status: 'canonical' },
  { name: 'ai-agent-badge', file: 'ui/ai-agent-badge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'ai-context-summary', file: 'ui/ai-context-summary.tsx', section: 'App Components', status: 'canonical' },
  { name: 'ai-execution-badge', file: 'ui/ai-execution-badge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'alert', file: 'ui/alert.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'alert-dialog', file: 'ui/alert-dialog.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'anchored-menu', file: 'ui/anchored-menu.tsx', section: 'Primitives', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——与 ui/menu 能力重叠，锚定下拉统一走 menu / dropdown-menu', proposal: 'delete' } },
  { name: 'app-dock', file: 'ui/app-dock.tsx', section: 'App Components', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '自研长尾：消费方 1（bottom-dock），与 shared/components/bottom-dock 能力重叠', proposal: 'delete' } },
  { name: 'aspect-ratio', file: 'ui/aspect-ratio.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'async-state', file: 'ui/async-state.tsx', section: 'App Components', status: 'canonical' },
  { name: 'autocomplete', file: 'ui/autocomplete.tsx', section: 'Primitives', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '消费方仅 1（命令面板），与 ui/combobox 能力重叠（输入过滤 + 建议列表）', proposal: 'merge', target: 'combobox' } },
  { name: 'avatar', file: 'ui/avatar.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'avatar-picker-field', file: 'ui/avatar-picker-field.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'badge', file: 'ui/badge.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'breadcrumb', file: 'ui/breadcrumb.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'button', file: 'ui/button.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'button-group', file: 'ui/button-group.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: 'F 类 F9.3 已结案（2026-09-29）：分裂按钮（主动作+下拉变体）是唯一合法场景，休眠原语不推广不清退；首个分裂按钮场景出现时启用', proposal: 'keep' } },
  { name: 'calendar', file: 'ui/calendar.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（react-day-picker 封装），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'card', file: 'ui/card.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'chapter-scrubber', file: 'ui/chapter-scrubber.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'chart', file: 'ui/chart.tsx', section: 'App Components', status: 'canonical' },
  { name: 'checkbox', file: 'ui/checkbox.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'checkbox-group', file: 'ui/checkbox-group.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'collapsible', file: 'ui/collapsible.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'color-picker', file: 'ui/color-picker.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'combobox', file: 'ui/combobox.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'command', file: 'ui/command.tsx', section: 'App Components', status: 'canonical' },
  { name: 'context-menu', file: 'ui/context-menu.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'data-list', file: 'ui/data-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'data-table', file: 'ui/data-table.tsx', section: 'App Components', status: 'canonical' },
  { name: 'data-table-shell', file: 'ui/data-table-shell.tsx', section: 'App Components', status: 'canonical' },
  { name: 'date-picker', file: 'ui/date-picker.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'dialog', file: 'ui/dialog.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'direction', file: 'ui/direction.tsx', section: 'Primitives', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——base-ui DirectionProvider 再导出，当前无 RTL 需求', proposal: 'delete' } },
  { name: 'document-preview-dialog', file: 'ui/document-preview-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'drawer', file: 'ui/drawer.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'dropdown-menu', file: 'ui/dropdown-menu.tsx', section: 'Primitives', status: 'deprecated', expiresAt: '2026-12-31', review: { pending: true, reason: '与 ui/menu（coss 配方，唯一菜单实现）双轨。2026-09-27 批 3 实物 API 比对结论：**差异大、非直接替换件**——Content 缺省 align 为 start 对 center、条目排版成体系不同、Checkbox/RadioItem 缺 inset、Shortcut 为 span 对 kbd、SubContent 定位不同，且本件 data-slot 槽位被 shared/lib/floating-layers.ts 生产依赖。2026-09-28 裁决 A：已扩 gen-components-md.mjs 解析 expiresAt，原先「生成器不认该槽位、写入即被丢弃」的工具互斥**已解除**，本件正式置 deprecated 限期迁移（至 2026-12-31）；迁移指引见 ui/dropdown-menu.tsx 文件头。', proposal: 'merge', target: 'menu' } },
  { name: 'dual-track-metric-pill', file: 'ui/dual-track-metric-pill.tsx', section: 'App Components', status: 'canonical' },
  { name: 'empty-state', file: 'ui/empty-state.tsx', section: 'App Components', status: 'canonical' },
  { name: 'error-boundary', file: 'ui/error-boundary.tsx', section: 'App Components', status: 'canonical' },
  { name: 'field', file: 'ui/field.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'filter-chips', file: 'ui/filter-chips.tsx', section: 'App Components', status: 'canonical' },
  { name: 'floating-dock', file: 'ui/floating-dock.tsx', section: 'App Components', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '自研长尾：零引用（仅画廊），与 shared/components/bottom-dock 能力重叠', proposal: 'delete' } },
  { name: 'form', file: 'ui/form.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'global-loading-state', file: 'ui/global-loading-state.tsx', section: 'App Components', status: 'canonical' },
  { name: 'header-action-button', file: 'ui/header-action-button.tsx', section: 'App Components', status: 'canonical' },
  { name: 'hover-card', file: 'ui/hover-card.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'icon-metric', file: 'ui/icon-metric.tsx', section: 'App Components', status: 'canonical' },
  { name: 'icon-stack', file: 'ui/icon-stack.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'input', file: 'ui/input.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'input-group', file: 'ui/input-group.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'input-otp', file: 'ui/input-otp.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（input-otp 库封装），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'item', file: 'ui/item.tsx', section: 'App Components', status: 'canonical' },
  { name: 'kbd', file: 'ui/kbd.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'label', file: 'ui/label.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'loading-overlay', file: 'ui/loading-overlay.tsx', section: 'App Components', status: 'canonical' },
  { name: 'menu', file: 'ui/menu.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'menu-surface', file: 'ui/menu-surface.ts', section: 'Primitives', status: 'canonical' },
  { name: 'menubar', file: 'ui/menubar.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'meter', file: 'ui/meter.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '自研长尾：零引用（仅画廊），coss 来源件，方案倾向保留为 standby', proposal: 'standby' } },
  { name: 'mock-badge', file: 'ui/mock-badge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'select-field', file: 'ui/select-field.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'navigation-menu', file: 'ui/navigation-menu.tsx', section: 'Primitives', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——横向导航由 menu / breadcrumb / tabs 承载', proposal: 'delete' } },
  { name: 'number-field', file: 'ui/number-field.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '自研长尾：零引用（仅画廊），coss 来源件，方案倾向保留为 standby', proposal: 'standby' } },
  { name: 'page-error-fallback', file: 'ui/page-error-fallback.tsx', section: 'App Components', status: 'canonical' },
  { name: 'page-header', file: 'ui/page-header.tsx', section: 'App Components', status: 'canonical' },
  { name: 'page-shell', file: 'ui/page-shell.tsx', section: 'App Components', status: 'canonical' },
  { name: 'pagination', file: 'ui/pagination.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'popover', file: 'ui/popover.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'progress', file: 'ui/progress.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'property-panel', file: 'ui/property-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'quick-cards-toggle', file: 'ui/quick-cards-toggle.tsx', section: 'App Components', status: 'canonical' },
  { name: 'radio-group', file: 'ui/radio-group.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'right-sidebar', file: 'ui/right-sidebar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'scroll-area', file: 'ui/scroll-area.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'section-card', file: 'ui/section-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'segmented-control', file: 'ui/segmented-control.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'select', file: 'ui/select.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'separator', file: 'ui/separator.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'sheet', file: 'ui/sheet.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'sidebar', file: 'ui/sidebar.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——与 ui/sidebar-panel（消费方 6）能力重叠', proposal: 'delete' } },
  { name: 'sidebar-panel', file: 'ui/sidebar-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'skeleton', file: 'ui/skeleton.tsx', section: 'App Components', status: 'canonical' },
  { name: 'slider', file: 'ui/slider.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'sortable', file: 'ui/sortable.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'spinner', file: 'ui/spinner.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'stat-card', file: 'ui/stat-card.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '命名双轨：与 ui/stats-card（消费方 10）能力重叠，本件消费方仅 1', proposal: 'merge', target: 'stats-card' } },
  { name: 'stats-card', file: 'ui/stats-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'status-pill', file: 'ui/status-pill.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'stepper', file: 'ui/stepper.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'sub-page-toolbar', file: 'ui/sub-page-toolbar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'switch', file: 'ui/switch.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'tab-bar', file: 'ui/tab-bar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'table', file: 'ui/table.tsx', section: 'App Components', status: 'canonical' },
  { name: 'tabs', file: 'ui/tabs.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'textarea', file: 'ui/textarea.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'toast', file: 'ui/toast.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'toggle', file: 'ui/toggle.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'toggle-group', file: 'ui/toggle-group.tsx', section: 'Primitives', status: 'standby', reviewBy: '2026-10-31', review: { pending: true, reason: '官方注册表基线件（base-ui 配方），零引用（仅画廊），零维护成本', proposal: 'keep' } },
  { name: 'tone', file: 'ui/tone.ts', section: 'Primitives', status: 'canonical' },
  { name: 'toolbar-row', file: 'ui/toolbar-row.tsx', section: 'App Components', status: 'canonical' },
  { name: 'tooltip', file: 'ui/tooltip.tsx', section: 'Primitives', status: 'canonical' },
  { name: 'view-display-popover', file: 'ui/view-display-popover.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——与 ui/popover 能力重叠；唯一带测试的死件，测试一并列为候选', proposal: 'delete' } },

  // ── 跨模块业务组件：src/shared/components/ ───────────────────────────────
  { name: 'board-view', file: 'shared/components/board-view/board-view.tsx', section: 'App Components', status: 'canonical' },
  { name: 'bottom-dock', file: 'shared/components/bottom-dock/bottom-dock.tsx', section: 'App Components', status: 'canonical' },
  { name: 'dock-metric-badge', file: 'shared/components/bottom-dock/dock-metric-badge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'dock-user-popover', file: 'shared/components/bottom-dock/dock-user-popover.tsx', section: 'App Components', status: 'canonical' },
  { name: 'cell-select', file: 'shared/components/cell-select.tsx', section: 'App Components', status: 'canonical' },
  { name: 'connection-banner', file: 'shared/components/connection-banner.tsx', section: 'App Components', status: 'canonical' },
  { name: 'acceptance-criteria-field', file: 'shared/components/create-dialog/acceptance-criteria-field.tsx', section: 'App Components', status: 'canonical' },
  { name: 'agent-presence-banner', file: 'shared/components/create-dialog/agent-presence-banner.tsx', section: 'App Components', status: 'canonical' },
  { name: 'bug-template-helper', file: 'shared/components/create-dialog/entity-templates/bug-template-helper.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被自身 __tests__ 引用，无生产消费方', proposal: 'delete' } },
  { name: 'doc-category-chips', file: 'shared/components/create-dialog/entity-templates/doc-category-chips.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被自身 __tests__ 引用，无生产消费方', proposal: 'delete' } },
  { name: 'project-source-tabs', file: 'shared/components/create-dialog/entity-templates/project-source-tabs.tsx', section: 'App Components', status: 'canonical' },
  { name: 'create-dialog/index', file: 'shared/components/create-dialog/index.tsx', section: 'App Components', status: 'canonical' },
  { name: 'mode-shuttle-button', file: 'shared/components/create-dialog/mode-shuttle-button.tsx', section: 'App Components', status: 'canonical' },
  { name: 'property-pills-bar', file: 'shared/components/create-dialog/property-pills-bar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'suggestions-card', file: 'shared/components/create-dialog/suggestions-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'unified-create-dialog', file: 'shared/components/create-dialog/unified-create-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'emoji-picker', file: 'shared/components/emoji-picker/emoji-picker.tsx', section: 'App Components', status: 'canonical' },
  { name: 'favorite-toggle', file: 'shared/components/favorite-toggle.tsx', section: 'App Components', status: 'canonical' },
  { name: 'gantt-chart', file: 'shared/components/gantt-chart.tsx', section: 'App Components', status: 'canonical' },
  { name: 'global-create-dialog', file: 'shared/components/global-create-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'issue-type-icon', file: 'shared/components/issue-type-icon.tsx', section: 'App Components', status: 'canonical' },
  { name: 'issue-type-pill', file: 'shared/components/issue-type-pill.tsx', section: 'App Components', status: 'canonical' },
  { name: 'language-switcher', file: 'shared/components/language-switcher.tsx', section: 'App Components', status: 'canonical' },
  { name: 'markdown-editor', file: 'shared/components/markdown-editor.tsx', section: 'App Components', status: 'canonical' },
  { name: 'markdown-live-editor', file: 'shared/components/markdown-live-editor.tsx', section: 'App Components', status: 'canonical' },
  { name: 'markdown-view', file: 'shared/components/markdown-view.tsx', section: 'App Components', status: 'canonical' },
  { name: 'prompt-editor', file: 'shared/components/prompt-editor.tsx', section: 'App Components', status: 'canonical' },

  // ── 错位目录：src/shared/ui/（E7 清退候选） ───────────────────────────────
  { name: 'filter-panel', file: 'shared/ui/filter-panel.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——唯一引用是 project-list-page.test.tsx 的 vi.mock；且构成第二个 ui 命名空间', proposal: 'delete' } },

  // ── 模块专用组件：src/modules/*/components/ ──────────────────────────────
  { name: 'acceptance-draft-dialog', file: 'modules/acceptance/components/acceptance-draft-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'acceptance-form-dialog', file: 'modules/acceptance/components/acceptance-form-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'audit-report-panel', file: 'modules/acceptance/components/audit-report-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'activity-comment', file: 'modules/activity/components/activity-comment.tsx', section: 'App Components', status: 'canonical' },
  { name: 'activity-feed', file: 'modules/activity/components/activity-feed.tsx', section: 'App Components', status: 'canonical' },
  { name: 'comment-input', file: 'modules/activity/components/comment-input.tsx', section: 'App Components', status: 'canonical' },
  { name: 'reaction-bar', file: 'modules/activity/components/reaction-bar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'generated-password-dialog', file: 'modules/admin/components/generated-password-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'invite-create-dialog', file: 'modules/admin/components/invite-create-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'invites-section', file: 'modules/admin/components/invites-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'members-section', file: 'modules/admin/components/members-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'user-accounts-section', file: 'modules/admin/components/user-accounts-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'user-create-dialog', file: 'modules/admin/components/user-create-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'user-edit-dialog', file: 'modules/admin/components/user-edit-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'central-watch-dial', file: 'modules/ai-surface/components/central-watch-dial.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'decision-queue-panel', file: 'modules/ai-surface/components/decision-queue-panel.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'omni-dock', file: 'modules/ai-surface/components/omni-dock.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'pipeline-lane-strip', file: 'modules/ai-surface/components/pipeline-lane-strip.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'radial-watch-deck', file: 'modules/ai-surface/components/radial-watch-deck.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'sample-tag', file: 'modules/ai-surface/components/sample-tag.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'screenplay-controls', file: 'modules/ai-surface/components/screenplay-controls.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'surface-liveness', file: 'modules/ai-surface/components/surface-liveness.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'surface-narration-bar', file: 'modules/ai-surface/components/surface-narration-bar.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'anchor-qa-thread', file: 'modules/assistant/components/anchor-qa-thread.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-colleague-slot', file: 'modules/assistant/components/assistant-colleague-slot.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-context-chip', file: 'modules/assistant/components/assistant-context-chip.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-decision-strip', file: 'modules/assistant/components/assistant-decision-strip.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-fab', file: 'modules/assistant/components/assistant-fab.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-history-menu', file: 'modules/assistant/components/assistant-history-menu.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-message-input', file: 'modules/assistant/components/assistant-message-input.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-message-list', file: 'modules/assistant/components/assistant-message-list.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-model-picker', file: 'modules/assistant/components/assistant-model-picker.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-opening-report', file: 'modules/assistant/components/assistant-opening-report.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-panel', file: 'modules/assistant/components/assistant-panel.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-quick-prompts', file: 'modules/assistant/components/assistant-quick-prompts.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-run-line', file: 'modules/assistant/components/assistant-run-line.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-status-dot', file: 'modules/assistant/components/assistant-status-dot.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'assistant-tool-card', file: 'modules/assistant/components/assistant-tool-card.tsx', section: 'AI Execution', status: 'canonical' },
  { name: 'thinking-stream', file: 'modules/assistant/components/thinking-stream.tsx', section: 'AI Execution', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被设计系统页引用，无模块内消费方', proposal: 'delete' } },
  { name: 'admin-guard', file: 'modules/auth/components/admin-guard.tsx', section: 'App Components', status: 'canonical' },
  { name: 'auth-guard', file: 'modules/auth/components/auth-guard.tsx', section: 'App Components', status: 'canonical' },
  { name: 'auth-shell', file: 'modules/auth/components/auth-shell.tsx', section: 'App Components', status: 'canonical' },
  { name: 'auth-visual-card', file: 'modules/auth/components/auth-visual-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'auth-visual', file: 'modules/auth/components/auth-visual.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-card', file: 'modules/auth/components/member-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'server-config-dialog', file: 'modules/auth/components/server-config-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'blueprint-canvas', file: 'modules/auth/components/visuals/blueprint-canvas.tsx', section: 'App Components', status: 'canonical' },
  { name: 'prism-canvas', file: 'modules/auth/components/visuals/prism-canvas.tsx', section: 'App Components', status: 'canonical' },
  { name: 'boot-checklist', file: 'modules/boot/components/boot-checklist.tsx', section: 'App Components', status: 'canonical' },
  { name: 'boot-error-drawer', file: 'modules/boot/components/boot-error-drawer.tsx', section: 'App Components', status: 'canonical' },
  { name: 'boot-progress-bar', file: 'modules/boot/components/boot-progress-bar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'boot-toggle', file: 'modules/boot/components/boot-toggle.tsx', section: 'App Components', status: 'canonical' },
  { name: 'contract-bindings-panel', file: 'modules/contract/components/contract-bindings-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'role-manager', file: 'modules/core-config/components/role-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'status-manager', file: 'modules/core-config/components/status-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'tag-manager', file: 'modules/core-config/components/tag-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'template-manager', file: 'modules/core-config/components/template-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'decision-review-modal', file: 'modules/decision/components/decision-review-modal.tsx', section: 'App Components', status: 'canonical' },
  { name: 'decomposition-review-panel', file: 'modules/decision/components/decomposition-review-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'BackendStatusBadge', file: 'modules/desktop/components/BackendStatusBadge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'desktop-gate', file: 'modules/desktop/components/desktop-gate.tsx', section: 'App Components', status: 'canonical' },
  { name: 'desktop-log-card', file: 'modules/desktop/components/desktop-log-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'desktop-preferences-card', file: 'modules/desktop/components/desktop-preferences-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'process-monitor-card', file: 'modules/desktop/components/process-monitor-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'approval-dialog', file: 'modules/document/components/approval-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'document-properties-panel', file: 'modules/document/components/document-properties-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'document-task-links', file: 'modules/document/components/document-task-links.tsx', section: 'App Components', status: 'canonical' },
  { name: 'mdx-editor', file: 'modules/document/components/mdx-editor.tsx', section: 'App Components', status: 'canonical' },
  { name: 'mdx-renderer', file: 'modules/document/components/mdx-renderer.tsx', section: 'App Components', status: 'canonical' },
  { name: 'mdx-toolbar', file: 'modules/document/components/mdx-toolbar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'revision-impact-banner', file: 'modules/document/components/revision-impact-banner.tsx', section: 'App Components', status: 'canonical' },
  { name: 'section-navigation', file: 'modules/document/components/section-navigation.tsx', section: 'App Components', status: 'canonical' },
  { name: 'section-task-links-list', file: 'modules/document/components/section-task-links-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-picker-dialog', file: 'modules/document/components/task-picker-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'version-diff-view', file: 'modules/document/components/version-diff-view.tsx', section: 'App Components', status: 'canonical' },
  { name: 'version-history-panel', file: 'modules/document/components/version-history-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-details-dialog', file: 'modules/executions/components/run-details-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-diagnosis-section', file: 'modules/executions/components/run-diagnosis-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-event-list', file: 'modules/executions/components/run-event-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-info-panel', file: 'modules/executions/components/run-info-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-overview-card', file: 'modules/executions/components/run-overview-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-status', file: 'modules/executions/components/run-status.tsx', section: 'App Components', status: 'canonical' },
  { name: 'run-timeline', file: 'modules/executions/components/run-timeline.tsx', section: 'App Components', status: 'canonical' },
  { name: 'step-detail-panel', file: 'modules/executions/components/step-detail-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'bind-repository-dialog', file: 'modules/git/components/bind-repository-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'branch-list', file: 'modules/git/components/branch-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'commit-list', file: 'modules/git/components/commit-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'diff-viewer', file: 'modules/git/components/diff-viewer.tsx', section: 'App Components', status: 'canonical' },
  { name: 'git-command-panel', file: 'modules/git/components/git-command-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'git-tool-status', file: 'modules/git/components/git-tool-status.tsx', section: 'App Components', status: 'canonical' },
  { name: 'pull-request-card', file: 'modules/git/components/pull-request-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'pull-request-list', file: 'modules/git/components/pull-request-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'repository-list', file: 'modules/git/components/repository-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workspace-config', file: 'modules/git/components/workspace-config.tsx', section: 'App Components', status: 'canonical' },
  { name: 'github-config-form', file: 'modules/github/components/github-config-form.tsx', section: 'App Components', status: 'canonical' },
  { name: 'github-panel', file: 'modules/github/components/github-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'github-setup-card', file: 'modules/github/components/github-setup-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'analysis-draft-dialog', file: 'modules/intake/components/analysis-draft-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'pipeline-overview-cards', file: 'modules/intake/components/pipeline-overview-cards.tsx', section: 'App Components', status: 'canonical' },
  { name: 'readiness-dialog', file: 'modules/intake/components/readiness-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'acceptance-criteria-preview', file: 'modules/issue/components/acceptance-criteria-preview.tsx', section: 'App Components', status: 'canonical' },
  { name: 'ai-assign-dialog', file: 'modules/issue/components/ai-assign-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'batch-create-tasks-dialog', file: 'modules/issue/components/batch-create-tasks-dialog.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——全库无 import，且不在画廊', proposal: 'delete' } },
  { name: 'batch-update-issues-dialog', file: 'modules/issue/components/batch-update-issues-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'board-presets', file: 'modules/issue/components/board-presets.tsx', section: 'App Components', status: 'canonical' },
  { name: 'bug-simple-list', file: 'modules/issue/components/bug-simple-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'cell-editors', file: 'modules/issue/components/cell-editors.tsx', section: 'App Components', status: 'canonical' },
  { name: 'completion-review', file: 'modules/issue/components/completion-review.tsx', section: 'App Components', status: 'canonical' },
  { name: 'custom-field-input', file: 'modules/issue/components/custom-field-input.tsx', section: 'App Components', status: 'canonical' },
  { name: 'execution-items-panel', file: 'modules/issue/components/execution-items-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'global-task-export-dialog', file: 'modules/issue/components/global-task-export-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'issue-dependencies-section', file: 'modules/issue/components/issue-dependencies-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'issue-type-switcher', file: 'modules/issue/components/issue-type-switcher.tsx', section: 'App Components', status: 'canonical' },
  { name: 'iteration-detail-dialog', file: 'modules/issue/components/iteration-detail-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'iteration-form-dialog', file: 'modules/issue/components/iteration-form-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-board', file: 'modules/issue/components/task-board.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——全库无 import（看板能力由 shared/components/board-view 承载），且不在画廊', proposal: 'delete' } },
  { name: 'task-detail-drawer', file: 'modules/issue/components/task-detail-drawer.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '孤儿组件：全库 0 importer（仅自身与测试文件引用）；F 类 §1.4 顺带发现，按 E1 制度转公示、公示期无人认领则清退', proposal: 'delete' } },
  { name: 'task-gantt', file: 'modules/issue/components/task-gantt.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-import-export', file: 'modules/issue/components/task-import-export.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-prompt-panel', file: 'modules/issue/components/task-prompt-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-rows', file: 'modules/issue/components/task-rows.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被自身测试与设计系统页引用', proposal: 'delete' } },
  { name: 'task-simple-list', file: 'modules/issue/components/task-simple-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-table-view', file: 'modules/issue/components/task-table-view.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-config-form', file: 'modules/linear/components/linear-config-form.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-conflict-resolver', file: 'modules/linear/components/linear-conflict-resolver.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-projects-table', file: 'modules/linear/components/linear-projects-table.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-provider-card', file: 'modules/linear/components/linear-provider-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-status-badge', file: 'modules/linear/components/linear-status-badge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-sync-log-drawer', file: 'modules/linear/components/linear-sync-log-drawer.tsx', section: 'App Components', status: 'canonical' },
  { name: 'linear-sync-log', file: 'modules/linear/components/linear-sync-log.tsx', section: 'App Components', status: 'canonical' },
  { name: 'sync-progress-dialog', file: 'modules/linear/components/sync-progress-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'task-linear-panel', file: 'modules/linear/components/task-linear-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'inbox-item-row', file: 'modules/notification/components/inbox-item-row.tsx', section: 'App Components', status: 'canonical' },
  { name: 'notification-settings-dialog', file: 'modules/notification/components/notification-settings-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'agent-handoff-card', file: 'modules/office/components/agent-handoff-card.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被设计系统页引用，无模块内消费方', proposal: 'delete' } },
  { name: 'collaboration-section', file: 'modules/office/components/collaboration-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'colleague-card', file: 'modules/office/components/colleague-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'onboarding-gate', file: 'modules/onboarding/components/onboarding-gate.tsx', section: 'App Components', status: 'canonical' },
  { name: 'api-doc-links-manager', file: 'modules/project/components/api-doc-links-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'ai-insight-card', file: 'modules/project/components/dashboard/ai-insight-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'integration-status-strip', file: 'modules/project/components/dashboard/integration-status-strip.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-detail-frame', file: 'modules/project/components/dashboard/project-detail-frame.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-detail-header-card', file: 'modules/project/components/dashboard/project-detail-header-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-detail-nav', file: 'modules/project/components/dashboard/project-detail-nav.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-health-score-dialog', file: 'modules/project/components/dashboard/project-health-score-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-overview-charts', file: 'modules/project/components/dashboard/project-overview-charts.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-right-sidebar', file: 'modules/project/components/dashboard/project-right-sidebar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-sidebar-context', file: 'modules/project/components/dashboard/project-sidebar-context.tsx', section: 'App Components', status: 'canonical' },
  { name: 'doc-links-manager', file: 'modules/project/components/doc-links-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'external-links-manager', file: 'modules/project/components/external-links-manager.tsx', section: 'App Components', status: 'canonical' },
  { name: 'grill-interview', file: 'modules/project/components/grill/grill-interview.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-entry-wizard', file: 'modules/project/components/import/project-entry-wizard.tsx', section: 'App Components', status: 'canonical' },
  { name: 'interview-chat', file: 'modules/project/components/playbook/interview-chat.tsx', section: 'App Components', status: 'canonical' },
  { name: 'interview-dialog', file: 'modules/project/components/playbook/interview-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'profile-atom-card', file: 'modules/project/components/profile/profile-atom-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'profile-completeness-ring', file: 'modules/project/components/profile/profile-completeness-ring.tsx', section: 'App Components', status: 'canonical' },
  { name: 'profile-health-chips', file: 'modules/project/components/profile/profile-health-chips.tsx', section: 'App Components', status: 'canonical' },
  { name: 'profile-slot-section', file: 'modules/project/components/profile/profile-slot-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-board', file: 'modules/project/components/project-board.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-cell-editors', file: 'modules/project/components/project-cell-editors.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-gantt', file: 'modules/project/components/project-gantt.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-linear-sync-status', file: 'modules/project/components/project-linear-sync-status.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-property-panel', file: 'modules/project/components/project-property-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-simple-list', file: 'modules/project/components/project-simple-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-team-bindings', file: 'modules/project/components/project-team-bindings.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-playbook-settings-panel', file: 'modules/project/components/settings/project-playbook-settings-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-prompt-settings-panel', file: 'modules/project/components/settings/project-prompt-settings-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-team-settings-panel', file: 'modules/project/components/settings/project-team-settings-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'project-roles-section', file: 'modules/project-role/components/project-roles-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'template-picker-dialog', file: 'modules/prompt/components/template-picker-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'release-deliverables-card', file: 'modules/release/components/release-deliverables-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'release-trace-section', file: 'modules/release/components/release-trace-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'mcp-tab', file: 'modules/settings/components/ai/mcp-tab.tsx', section: 'App Components', status: 'canonical' },
  { name: 'models-tab', file: 'modules/settings/components/ai/models-tab.tsx', section: 'App Components', status: 'canonical' },
  { name: 'overview-tab', file: 'modules/settings/components/ai/overview-tab.tsx', section: 'App Components', status: 'canonical' },
  { name: 'provider-visuals', file: 'modules/settings/components/ai/provider-visuals.tsx', section: 'App Components', status: 'canonical' },
  { name: 'skills-tab', file: 'modules/settings/components/ai/skills-tab.tsx', section: 'App Components', status: 'canonical' },
  { name: 'tools-tab', file: 'modules/settings/components/ai/tools-tab.tsx', section: 'App Components', status: 'canonical' },
  { name: 'storage-settings', file: 'modules/settings/components/storage-settings.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-avatar', file: 'modules/team-member/components/member-avatar.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-card-popover', file: 'modules/team-member/components/member-card-popover.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-card-team', file: 'modules/team-member/components/member-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-chip', file: 'modules/team-member/components/member-chip.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-create-dialog', file: 'modules/team-member/components/member-create-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-list', file: 'modules/team-member/components/member-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-picker', file: 'modules/team-member/components/member-picker.tsx', section: 'App Components', status: 'canonical' },
  { name: 'member-tool-grants', file: 'modules/team-member/components/member-tool-grants.tsx', section: 'App Components', status: 'canonical' },
  { name: 'mention-renderer', file: 'modules/team-member/components/mention-renderer.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被设计系统页引用；mention 渲染实际走 MarkdownView', proposal: 'delete' } },
  { name: 'mention-textarea', file: 'modules/team-member/components/mention-textarea.tsx', section: 'App Components', status: 'review', reviewBy: '2026-10-31', review: { pending: true, reason: '零引用（实测）——仅被设计系统页与一处 vi.mock 引用', proposal: 'delete' } },
  { name: 'team-card', file: 'modules/team-member/components/team-card.tsx', section: 'App Components', status: 'canonical' },
  { name: 'team-create-dialog', file: 'modules/team-member/components/team-create-dialog.tsx', section: 'App Components', status: 'canonical' },
  { name: 'team-hierarchy-section', file: 'modules/team-member/components/team-hierarchy-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'team-list', file: 'modules/team-member/components/team-list.tsx', section: 'App Components', status: 'canonical' },
  { name: 'team-prompt-section', file: 'modules/team-member/components/team-prompt-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'team-stats-section', file: 'modules/team-member/components/team-stats-section.tsx', section: 'App Components', status: 'canonical' },
  { name: 'trust-level-badge', file: 'modules/team-member/components/trust-level-badge.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workflow-canvas', file: 'modules/workflow/components/workflow-canvas.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workflow-node-palette', file: 'modules/workflow/components/workflow-node-palette.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workflow-run-panel', file: 'modules/workflow/components/workflow-run-panel.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workflow-run-timeline', file: 'modules/workflow/components/workflow-run-timeline.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workflow-step-editor', file: 'modules/workflow/components/workflow-step-editor.tsx', section: 'App Components', status: 'canonical' },
  { name: 'workflow-trigger-dialog', file: 'modules/workflow/components/workflow-trigger-dialog.tsx', section: 'App Components', status: 'canonical' },
]
