// 预设命令定义
import type { CommandItem, AICommandTemplate } from '../types/command.types';

export const presetCommands: CommandItem[] = [
  // ==================== 导航命令 (Navigation) ====================
  {
    id: 'nav.projects',
    label: '打开项目列表',
    description: '跳转到项目管理页面',
    keywords: ['projects', '项目', 'list'],
    icon: 'FolderKanban',
    shortcut: ['G', 'P'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/projects' },
  },
  {
    id: 'nav.dashboard',
    label: '打开仪表盘',
    description: '跳转到仪表盘页面',
    keywords: ['dashboard', '仪表盘', 'home'],
    icon: 'LayoutDashboard',
    shortcut: ['G', 'D'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/projects/dashboard' },
  },
  {
    id: 'nav.ai-space',
    label: '打开 AI 管理',
    description: '跳转到 AI 管理页面',
    keywords: ['ai', 'chat', 'management', '管理'],
    icon: 'Sparkles',
    shortcut: ['G', 'A'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/ai' },
  },
  {
    id: 'nav.documents',
    label: '打开文档中心',
    description: '跳转到文档管理页面',
    keywords: ['documents', 'docs', '文档'],
    icon: 'FileText',
    shortcut: ['G', 'O'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/documents' },
  },
  {
    id: 'nav.terminal',
    label: '打开终端',
    description: '跳转到终端页面',
    keywords: ['terminal', '终端', 'shell'],
    icon: 'Terminal',
    shortcut: ['G', 'T'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/terminal' },
  },
  {
    id: 'nav.repositories',
    label: '打开仓库',
    description: '跳转到 Git 仓库页面',
    keywords: ['git', 'repo', 'repository', '仓库'],
    icon: 'GitBranch',
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/repositories' },
  },
  {
    id: 'nav.integrations',
    label: '打开集成',
    description: '跳转到第三方集成页面',
    keywords: ['integrations', 'plugins', '集成', '插件'],
    icon: 'Puzzle',
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/integrations' },
  },
  {
    id: 'nav.notifications',
    label: '打开通知',
    description: '跳转到通知中心',
    keywords: ['notifications', '通知'],
    icon: 'Bell',
    shortcut: ['G', 'N'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/notifications' },
  },
  {
    id: 'nav.settings',
    label: '打开设置',
    description: '跳转到系统设置页面',
    keywords: ['settings', '设置', 'preferences'],
    icon: 'Settings',
    shortcut: ['G', 'S'],
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/settings' },
  },
  {
    id: 'nav.analytics',
    label: '打开分析',
    description: '跳转到数据分析页面',
    keywords: ['analytics', 'analysis', '分析'],
    icon: 'BarChart3',
    group: '导航',
    type: 'navigation',
    scope: ['global'],
    action: { type: 'navigate', path: '/app/analytics' },
  },

  // ==================== 创建命令 (Create) ====================
  {
    id: 'create.project',
    label: '创建新项目',
    description: '创建一个新的项目',
    keywords: ['create', 'new', 'project', '创建', '新建'],
    icon: 'Plus',
    shortcut: ['Ctrl', 'Shift', 'P'],
    group: '创建',
    type: 'action',
    scope: ['global'],
    action: { type: 'create', entity: 'project' },
  },
  {
    id: 'create.task',
    label: '创建新任务',
    description: '在当前项目中创建新任务',
    keywords: ['create', 'new', 'task', '任务'],
    icon: 'CheckSquare',
    shortcut: ['Ctrl', 'Shift', 'T'],
    group: '创建',
    type: 'action',
    scope: ['project'],
    action: { type: 'create', entity: 'task' },
  },
  {
    id: 'create.document',
    label: '创建新文档',
    description: '创建一个新的文档',
    keywords: ['create', 'new', 'document', 'doc', '文档'],
    icon: 'FilePlus',
    shortcut: ['Ctrl', 'Shift', 'N'],
    group: '创建',
    type: 'action',
    scope: ['global', 'project'],
    action: { type: 'create', entity: 'document' },
  },

  // ==================== AI 命令 (AI) ====================
  {
    id: 'ai.analyze-project',
    label: '分析当前项目',
    description: '使用 AI 分析当前项目的状态、进度和风险',
    keywords: ['ai', 'analyze', 'analysis', 'project', '分析'],
    icon: 'Sparkles',
    shortcut: ['Ctrl', 'Shift', 'A'],
    group: 'AI 操作',
    type: 'ai',
    scope: ['project'],
    action: { type: 'ai-chat', prompt: '请分析这个项目的当前状态，包括：\n1. 整体进度评估\n2. 关键风险点\n3. 改进建议', context: 'current-project' },
  },
  {
    id: 'ai.explain-selection',
    label: '解释选中内容',
    description: 'AI 解释当前选中的代码或文本',
    keywords: ['ai', 'explain', '解释', '代码'],
    icon: 'MessageSquare',
    shortcut: ['Ctrl', 'Shift', 'E'],
    group: 'AI 操作',
    type: 'ai',
    scope: ['global', 'project'],
    action: { type: 'ai-explain', target: 'selection' },
  },
  {
    id: 'ai.generate-commit',
    label: '生成提交信息',
    description: '根据当前代码变更生成 Git 提交信息',
    keywords: ['git', 'commit', 'message', '提交'],
    icon: 'GitCommit',
    group: 'AI 操作',
    type: 'ai',
    scope: ['global', 'project'],
    action: { type: 'ai-generate', template: 'commit-message' },
  },
  {
    id: 'ai.generate-pr',
    label: '生成 PR 描述',
    description: '根据提交生成 Pull Request 描述',
    keywords: ['pr', 'pull', 'request', '描述'],
    icon: 'GitPullRequest',
    group: 'AI 操作',
    type: 'ai',
    scope: ['global', 'project'],
    action: { type: 'ai-generate', template: 'pr-description' },
  },
  {
    id: 'ai.generate-tests',
    label: '生成测试用例',
    description: '为当前文件或选中代码生成测试用例',
    keywords: ['test', 'testing', '测试', '用例'],
    icon: 'TestTube',
    group: 'AI 操作',
    type: 'ai',
    scope: ['global', 'project'],
    action: { type: 'ai-generate', template: 'test-case' },
  },
  {
    id: 'ai.task-from-doc',
    label: '从文档创建任务',
    description: '分析文档内容，提取任务项',
    keywords: ['document', 'task', 'from', '文档', '任务'],
    icon: 'FileDown',
    group: 'AI 操作',
    type: 'ai',
    scope: ['document'],
    action: { type: 'ai-generate', template: 'task-from-doc' },
  },

  // ==================== 设置命令 (Settings) ====================
  {
    id: 'settings.toggle-theme',
    label: '切换主题',
    description: '在亮色/暗色主题间切换',
    keywords: ['theme', 'dark', 'light', '主题', '暗色'],
    icon: 'Moon',
    shortcut: ['T'],
    group: '设置',
    type: 'setting',
    scope: ['global'],
    action: { type: 'toggle', target: 'theme' },
  },
  {
    id: 'settings.toggle-sidebar',
    label: '切换侧边栏',
    description: '展开/收起侧边栏',
    keywords: ['sidebar', '侧边栏', 'toggle'],
    icon: 'PanelLeft',
    group: '设置',
    type: 'setting',
    scope: ['global'],
    action: { type: 'toggle', target: 'sidebar' },
  },
  {
    id: 'settings.open-shortcuts',
    label: '打开快捷键设置',
    description: '查看和配置所有快捷键',
    keywords: ['shortcuts', 'keyboard', '快捷键'],
    icon: 'Keyboard',
    group: '设置',
    type: 'setting',
    scope: ['global'],
    action: { type: 'open-modal', modal: 'shortcuts' },
  },

  // ==================== 搜索命令 (Search) ====================
  {
    id: 'search.global',
    label: '全局搜索',
    description: '搜索项目、任务、文档等内容',
    keywords: ['search', 'find', '搜索', '查找'],
    icon: 'Search',
    shortcut: ['Ctrl', 'Shift', 'F'],
    group: '搜索',
    type: 'search',
    scope: ['global'],
    action: { type: 'open-modal', modal: 'global-search' },
  },
  {
    id: 'search.tasks',
    label: '搜索任务',
    description: '在当前项目中搜索任务',
    keywords: ['search', 'task', '任务', 'find'],
    icon: 'CheckSquare',
    group: '搜索',
    type: 'search',
    scope: ['project'],
    action: { type: 'open-modal', modal: 'task-search' },
  },
  {
    id: 'search.documents',
    label: '搜索文档',
    description: '搜索文档和章节',
    keywords: ['search', 'document', 'docs', '文档'],
    icon: 'FileText',
    group: '搜索',
    type: 'search',
    scope: ['global', 'project'],
    action: { type: 'open-modal', modal: 'document-search' },
  },
];

// AI 命令模板
export const aiCommandTemplates: AICommandTemplate[] = [
  {
    id: 'analyze-project',
    label: '分析项目',
    prompt: '请分析这个项目的当前状态，包括整体进度、关键风险和改进建议。',
    context: 'current-project',
    icon: 'Sparkles',
  },
  {
    id: 'summarize-task',
    label: '总结任务',
    prompt: '请总结以下任务的内容和当前状态：',
    context: 'current-task',
    icon: 'ListChecks',
  },
  {
    id: 'extract-tasks',
    label: '提取任务',
    prompt: '请分析以下文档，提取其中的任务项和行动项：',
    context: 'current-document',
    icon: 'FileDown',
  },
  {
    id: 'explain-code',
    label: '解释代码',
    prompt: '请详细解释以下代码：\n',
    context: 'none',
    icon: 'MessageSquare',
  },
  {
    id: 'review-code',
    label: '审查代码',
    prompt: '请审查以下代码，指出潜在问题和改进建议：\n',
    context: 'none',
    icon: 'Code2',
  },
  {
    id: 'generate-docs',
    label: '生成文档',
    prompt: '请根据以下内容生成文档：',
    context: 'none',
    icon: 'FileText',
  },
];

// 获取特定类型的命令
export function getCommandsByType(type: string): CommandItem[] {
  return presetCommands.filter((cmd) => cmd.type === type);
}

// 获取特定分组的命令
export function getCommandsByGroup(group: string): CommandItem[] {
  return presetCommands.filter((cmd) => cmd.group === group);
}
